server:
  port: "8080"

db:
  data_source_name: "courier.db"

models:
  - name: qwen-turbo
    provider: qwen
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key: ${QWEN_API_KEY}
#  - name: deepseek-chat
#    provider: deepseek
#    base_url: https://api.deepseek.com/v1
#    api_key: ${DEEPSEEK_API_KEY}

